# -*- coding: utf-8 -*-
"""Comparing_two_models_for ranking_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VEcyIOYu7AeAJwndhGT-hHYLthsBBv1U
"""

import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from sentence_transformers import SentenceTransformer

df = pd.read_csv(
    "potential-talents - Aspiring human resources - seeking human resources.csv"
)

print("Shape:", df.shape)
df.head()

df = df.drop_duplicates(
    subset=df.columns.drop("id")
).reset_index(drop=True)

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z ]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def clean_connection(x):
    x = str(x)
    if "500+" in x:
        return 500
    return int(x)

df["job_title"] = df["job_title"].apply(clean_text)
df["connection"] = df["connection"].apply(clean_connection)

keywords = "aspiring human resources seeking human resources"

tfidf = TfidfVectorizer(stop_words="english")

tfidf_matrix = tfidf.fit_transform(df["job_title"])

keyword_vec = tfidf.transform([keywords])

df["tfidf_similarity"] = cosine_similarity(
    tfidf_matrix,
    keyword_vec
).flatten()

df["connection_score"] = df["connection"] / df["connection"].max()

df["tfidf_score"] = (
    0.85 * df["tfidf_similarity"] +
    0.15 * df["connection_score"]
)

model = SentenceTransformer("all-MiniLM-L6-v2")

job_embeddings = model.encode(df["job_title"].tolist())

keyword_embedding = model.encode([keywords])

df["sbert_similarity"] = cosine_similarity(
    job_embeddings,
    keyword_embedding
).flatten()

df["sbert_score"] = (
    0.85 * df["sbert_similarity"] +
    0.15 * df["connection_score"]
)

tfidf_ranked = df.sort_values(
    "tfidf_score",
    ascending=False
)[["id","job_title","tfidf_score"]]

print("TOP TF-IDF RESULTS:")
print(tfidf_ranked.head(10))

sbert_ranked = df.sort_values(
    "sbert_score",
    ascending=False
)[["id","job_title","sbert_score"]]

print("\nTOP SBERT RESULTS:")
print(sbert_ranked.head(10))

plt.figure(figsize=(10,5))

plt.hist(df["tfidf_score"], alpha=0.5, label="TF-IDF")
plt.hist(df["sbert_score"], alpha=0.5, label="SBERT")

plt.legend()
plt.title("TF-IDF vs SBERT Score Distribution")
plt.xlabel("Score")
plt.ylabel("Frequency")
plt.show()

print("Correlation between TF-IDF and SBERT scores:")

print(
    df[["tfidf_score","sbert_score"]].corr()
)

comparison = pd.DataFrame({
    "Model": ["TF-IDF", "Sentence-BERT"],
    "Strength": [
        "Keyword-based, fast, interpretable",
        "Semantic understanding, context-aware"
    ],
    "Weakness": [
        "Fails on synonyms",
        "Slightly heavier computation"
    ]
})

print(comparison)