# -*- coding: utf-8 -*-
"""sentence-bertipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WN0unFaQ9x1gv-GIcUGisvJlpzXwWBxR
"""

import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics.pairwise import cosine_similarity

from sentence_transformers import SentenceTransformer

df = pd.read_csv(
    "potential-talents - Aspiring human resources - seeking human resources.csv"
)

print("Original dataset shape:", df.shape)

df.head()

df = df.drop_duplicates(
    subset=df.columns.drop("id")
).reset_index(drop=True)

print("After removing duplicates:", df.shape)

def clean_connection(x):
    x = str(x)

    if "500+" in x:
        return 500

    return int(x)

df["connection"] = df["connection"].apply(clean_connection)

df["connection"].describe()

def clean_text(text):
    text = str(text).lower()

    text = re.sub(r'[^a-zA-Z ]', ' ', text)

    text = re.sub(r'\s+', ' ', text)

    return text.strip()

df["job_title"] = df["job_title"].apply(clean_text)

df["location"] = df["location"].apply(clean_text)

sns.histplot(df["connection"], bins=20)

plt.title("Distribution of Candidate Connections")

plt.xlabel("Connections")

plt.show()

df["contains_hr"] = df["job_title"].str.contains(
    "human resources"
)

sns.countplot(x="contains_hr", data=df)

plt.title("Candidates Containing 'Human Resources'")

plt.show()

print(
    "Candidates containing HR:",
    df["contains_hr"].sum()
)

keywords = [
    "aspiring human resources",
    "seeking human resources"
]

keyword_text = " ".join(keywords)

model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

job_embeddings = model.encode(
    df["job_title"].tolist()
)

keyword_embedding = model.encode(
    [keyword_text]
)

df["similarity"] = cosine_similarity(
    job_embeddings,
    keyword_embedding
).flatten()

df["connection_score"] = (
    df["connection"] /
    df["connection"].max()
)

df["initial_fit"] = (
    0.85 * df["similarity"] +
    0.15 * df["connection_score"]
)

initial_ranked = df.sort_values(
    by="initial_fit",
    ascending=False
)

print("Top 10 BEFORE Starring:\n")

print(
    initial_ranked[
        ["id","job_title","initial_fit"]
    ].head(10)
)

starred_id = 3

star_index = df[
    df["id"] == starred_id
].index[0]

star_vector = job_embeddings[
    star_index
]

df["star_similarity"] = cosine_similarity(
    job_embeddings,
    [star_vector]
).flatten()

df["final_score"] = (
    0.6 * df["initial_fit"] +
    0.4 * df["star_similarity"]
)

final_ranked = df.sort_values(
    by="final_score",
    ascending=False
)

print("\nTop 10 AFTER Starring:\n")

print(
    final_ranked[
        ["id","job_title","final_score"]
    ].head(10)
)

plt.figure(figsize=(8,5))

plt.hist(
    df["initial_fit"],
    alpha=0.5,
    label="Before Star"
)

plt.hist(
    df["final_score"],
    alpha=0.5,
    label="After Star"
)

plt.legend()

plt.title(
    "Ranking Score Distribution Before and After Starring"
)

plt.xlabel("Score")

plt.ylabel("Frequency")

plt.show()

threshold = 0.25

filtered_df = df[
    (df["initial_fit"] > threshold) |
    (df["contains_hr"] == True)
]

print(
    "Candidates remaining after filtering:",
    filtered_df.shape[0]
)

cutoff = df["initial_fit"].quantile(0.75)

filtered_dynamic = df[
    df["initial_fit"] >= cutoff
]

print(
    "Dynamic Cutoff Used:",
    cutoff
)

print(
    "Candidates after dynamic cutoff:",
    filtered_dynamic.shape[0]
)

sns.histplot(df["initial_fit"])

plt.axvline(
    cutoff,
    color="red",
    linestyle="--",
    label="Dynamic Cutoff"
)

plt.legend()

plt.title("Dynamic Cutoff Selection")

plt.show()

star_ids = [3, 10, 25]

star_indices = df[
    df["id"].isin(star_ids)
].index

star_vectors = job_embeddings[
    star_indices
]

multi_star_similarity = cosine_similarity(
    job_embeddings,
    star_vectors
).mean(axis=1)

df["multi_star_score"] = (
    0.6 * df["initial_fit"] +
    0.4 * multi_star_similarity
)

multi_star_ranked = df.sort_values(
    by="multi_star_score",
    ascending=False
)

print(
    "Top Candidates using Multi-Star Ranking:\n"
)

print(
    multi_star_ranked[
        ["id","job_title","multi_star_score"]
    ].head(10)
)

print("Original dataset:", df.shape[0])

print(
    "After threshold filtering:",
    filtered_df.shape[0]
)

print(
    "After dynamic cutoff:",
    filtered_dynamic.shape[0]
)

final_ranked.to_csv(
    "final_ranked_sbert_candidates.csv",
    index=False
)

multi_star_ranked.to_csv(
    "multi_star_ranked_candidates.csv",
    index=False
)